CREATE TABLE kittycats (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    breed TEXT NOT NULL,
    description TEXT,
    url TEXT NOT NULL
);

CREATE TABLE fishies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    species TEXT NOT NULL,
    description TEXT
);

CREATE TABLE gumballs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    color TEXT NOT NULL,
    flavor TEXT NOT NULL
);

CREATE TABLE mantis_shrimpies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    species TEXT NOT NULL,
    description TEXT
);

CREATE TABLE sorting_algorithms (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);